# Write gitignored cam-secrets.json + cam-config.local.js, smoke-test Snap (token auth).
# Browser uses http://localhost:8080/cam/snap (dev-server proxy) — not the camera password URL.
# Usage:
#   cd C:\Users\jlay\Grok\flock-yeah
#   powershell -File scripts\link-cam.ps1 -Password 'yourpass'
#   powershell -File scripts\link-cam.ps1 -User admin -Password 'yourpass'
param(
  [string]$HostIp = "192.168.68.118",
  [string]$User = "admin",
  [Parameter(Mandatory = $true)][string]$Password,
  [int]$ProxyPort = 8080
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Get-ReolinkToken {
  param($HostIp, $User, $Password)
  $loginUrl = "http://$HostIp/cgi-bin/api.cgi?cmd=Login"
  # Reolink requires a JSON *array*. Piping a 1-item array into ConvertTo-Json
  # collapses it to a bare object, which returns rspCode -6 "please login first".
  $bodyObj = @(
    @{
      cmd = "Login"
      param = @{
        User = @{
          userName = $User
          password = $Password
        }
      }
    }
  )
  $json = ConvertTo-Json -InputObject $bodyObj -Depth 6 -Compress
  Write-Host "Logging in as '$User' @ $HostIp ..."
  Write-Host ("Login body shape: " + $(if ($json.StartsWith("[")) { "array OK" } else { "NOT ARRAY - $json" }))
  $r = Invoke-WebRequest -Uri $loginUrl -Method Post -Body ([System.Text.Encoding]::UTF8.GetBytes($json)) -ContentType "application/json" -UseBasicParsing -TimeoutSec 10
  $data = $r.Content | ConvertFrom-Json
  $row = if ($data -is [System.Array]) { $data[0] } else { $data }
  if ($row.code -ne 0) {
    $detail = $row.error.detail
    $remain = $row.error.auth_warning_info.remain_times
    throw "Login failed ($detail). Remaining tries: $remain. Check username/password in the Reolink app."
  }
  $token = $row.value.Token.name
  if (-not $token) { throw "Login OK but no token in response." }
  return $token
}

function Test-ReolinkSnap {
  param($HostIp, $Token)
  $snap = "http://$HostIp/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=flockyeah&token=$([uri]::EscapeDataString($Token))"
  Write-Host "Testing Snap with token..."
  $r = Invoke-WebRequest -Uri $snap -UseBasicParsing -TimeoutSec 10
  $ct = $r.Headers["Content-Type"]
  if ($ct -notmatch "image") {
    Write-Host "FAIL: Snap returned $ct. Body:"
    Write-Host $r.Content.Substring(0, [Math]::Min(400, $r.Content.Length))
    throw "Snap did not return an image."
  }
  Write-Host ("OK Snap image bytes=" + $r.RawContentLength)
}

try {
  $token = Get-ReolinkToken -HostIp $HostIp -User $User -Password $Password
  Write-Host ("OK token length=" + $token.Length)
  Test-ReolinkSnap -HostIp $HostIp -Token $token
} catch {
  Write-Host ("FAIL: " + $_.Exception.Message)
  Write-Host ""
  Write-Host "Tips:"
  Write-Host "  - Password is the camera password from the Reolink app (not your Reolink cloud account)."
  Write-Host "  - Default user is usually 'admin'. Try: -User admin"
  Write-Host "  - Special characters in the password are fine when quoted: -Password 'p@ss'"
  Write-Host "  - Confirm login works at http://$HostIp/ in a browser first."
  Write-Host "  - If you see 'Login has been locked', wait 10-30 min (or unlock in the Reolink app) before retrying."
  exit 1
}

# Secrets for the Node snap proxy only (never loaded in the browser).
$secrets = @{
  host     = $HostIp
  user     = $User
  password = $Password
  channel  = 0
} | ConvertTo-Json -Compress
# UTF-8 without BOM so Node JSON.parse does not choke
[System.IO.File]::WriteAllText((Join-Path $Root "cam-secrets.json"), $secrets, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote cam-secrets.json (gitignored)."

# Browser config: point Nest Cam A at the local proxy (no camera password in JS).
$out = @"
/**
 * LOCAL ONLY - gitignored. Generated by scripts/link-cam.ps1
 * Snapshots come from the dev server proxy (token auth) — not the camera URL.
 */
(function (global) {
  "use strict";
  const local = {
    discovery: {
      host: "$HostIp",
      vendor: "Reolink",
      mac: "EC-71-DB-19-18-56",
      openPorts: [80, 554, 8000, 9000],
      notes: "Local override active - Nest Cam A via /cam/snap proxy.",
    },
    streams: {
      henrietta: {
        mode: "snapshot",
        label: "Test Reolink (live)",
        snapshotUrl: "http://127.0.0.1:$ProxyPort/cam/snap",
        rtspHint: "rtsp://USER:PASS@$HostIp:554/h264Preview_01_sub",
        refreshMs: 2000,
      },
    },
    proxyBase: "http://127.0.0.1:$ProxyPort",
  };
  const base = global.CamConfig || {};
  global.CamConfig = Object.assign({}, base, local, {
    discovery: Object.assign({}, base.discovery || {}, local.discovery),
    streams: Object.assign({}, base.streams || {}, local.streams),
  });
})(typeof window !== "undefined" ? window : globalThis);
"@
[System.IO.File]::WriteAllText((Join-Path $Root "js\cam-config.local.js"), $out, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote js/cam-config.local.js (gitignored) -> proxy URL."
Write-Host ""
Write-Host "Next:"
Write-Host "  1. Stop any old static server on port $ProxyPort"
Write-Host "  2. npm run dev   (or: powershell -File scripts\dev.ps1)"
Write-Host "  3. Hard-refresh http://localhost:$ProxyPort/hens.html"